ibarr: Fix build errors on RHEL7.6 system
Fix build errors below on RHEL7.6 (Maipo) sytem. For the nl errors,
that's because the system has both and libnl-devel and libnl3-devel
installed.

  ip2gid/src/ipr_server.c: In function ‘server_find_gid’:
  In file included from ip2gid/src/msg_check.c:6:0:
  ip2gid/src/ib_resolve.h:26:21: error: field ‘s4’ has incomplete type
  struct sockaddr_in s4;
                     ^
  ip2gid/src/ipr_server.c:48:3: warning: implicit declaration of function ‘rtnl_link_get_kernel’ [-Wimplicit-function-declaration]
    err = rtnl_link_get_kernel(priv->nl_sock, 0, ifa->ifa_name,
    ^
  ip2gid/src/ipr_server.c: In function ‘ipr_server_create’:
  ip2gid/src/ipr_server.c:151:2: warning: implicit declaration of function ‘nl_socket_alloc’ [-Wimplicit-function-declaration]
    priv->nl_sock = nl_socket_alloc();
    ^
  ip2gid/src/ipr_server.c:151:16: warning: assignment makes pointer from integer without a cast [enabled by default]
    priv->nl_sock = nl_socket_alloc();
		  ^
  ip2gid/src/ipr_server.c:154:2: warning: passing argument 1 of ‘nl_connect’ from incompatible pointer type [enabled by default]
    err = nl_connect(priv->nl_sock, NETLINK_ROUTE);
    ^
  In file included from /usr/include/netlink/route/link.h:15:0,
	           from ip2gid/src/ipr_server.c:11:
  /usr/include/netlink/netlink.h:40:14: note: expected ‘struct nl_handle *’ but argument is of type ‘struct nl_sock *’
    extern int   nl_connect(struct nl_handle *, int);
                 ^
 ip2gid/src/ipr_server.c:161:2: warning: implicit declaration of function ‘nl_socket_free’ [-Wimplicit-function-declaration]
    nl_socket_free(priv->nl_sock);
    ^
 make[2]: *** [CMakeFiles/ibarr.dir/src/msg_check.c.o] Error 1

Signed-off-by: Mark Zhang <markzhang@nvidia.com>